[versions]
ldlib = "1.0.35.a"
registrate = "MC1.21-1.3.0+67"
configuration = "3.1.0-neoforge"

jei = "19.21.0.247"
rei = "16.0.799"
emi = "1.1.21+1.21.1"
ae2 = "19.2.8"
kubejs = "2101.7.1-build.181"
rhino = "2101.2.7-build.74"
architectury = "13.0.8"
clothconfig = "15.0.140"
theoneprobe = "1.21_neo-12.0.4-6"
curios = "9.4.2+1.21.1"
kotlinforforge = "5.7.0"
shimmer = "1.20.1-0.2.4"
journeyMapApi = "2.0.0-1.21.1-SNAPSHOT"
ftblibrary = "2101.1.12"
ftbteams = "2101.1.2"
ftbquests = "2101.1.8"
ftbchunks = "2101.1.8"
ccTweaked = "1.116.0"
resourcefullib = "3.0.12"
gamestages = "17.0.1"
bookshelf = "21.1.56"
ae2wtlib = "19.2.2"
argonauts = "1.2.4"
# FIXME for some reason their maven only has versions up to 1.1.10?
heracles = "1.1.10"

## modrinth maven ##
jade = "15.10.0+neoforge"
sodium = "mc1.21.1-0.6.13-neoforge"
iris = "1.8.8+1.21.1-neoforge"
modernfix = "4SPHwiDB" # 5.24.3+mc1.21.1

## cursemaven ##
worldStripper = "5592921"
javd = "5711894"
trenzalore = "5623160"
xaerosWorldMap = "6212662"
xaerosMinimap = "6306189"
journeyMap = "6383889"
spark = "6225208"
observable = "5733591"
ftblibrary-cm = "6304123"
ftbteams-cm = "6119437"
ftbquests-cm = "6371007"
ftbchunks-cm = "6295696"


[libraries]
ldlib               = { module = "com.lowdragmc.ldlib:ldlib-neoforge-1.21.1", version.ref = "ldlib" }
registrate          = { module = "com.tterrag.registrate:Registrate", version.ref = "registrate" }
configuration       = { module = "dev.toma.configuration:configuration-1.21.1", version.ref = "configuration" }

jei-common-api      = { module = "mezz.jei:jei-1.21.1-common-api", version.ref = "jei" }
jei-neoforge-api    = { module = "mezz.jei:jei-1.21.1-neoforge-api", version.ref = "jei" }
jei-neoforge-impl   = { module = "mezz.jei:jei-1.21.1-neoforge", version.ref = "jei" }
rei-plugin          = { module = "me.shedaniel:RoughlyEnoughItems-default-plugin-neoforge", version.ref = "rei" }
rei-api             = { module = "me.shedaniel:RoughlyEnoughItems-api-neoforge", version.ref = "rei" }
rei-neoforge        = { module = "me.shedaniel:RoughlyEnoughItems-neoforge", version.ref = "rei" }
emi                 = { module = "dev.emi:emi-neoforge", version.ref = "emi" }

ae2                 = { module = "org.appliedenergistics:appliedenergistics2", version.ref = "ae2" }
kubejs              = { module = "dev.latvian.mods:kubejs-neoforge", version.ref = "kubejs" }
rhino               = { module = "dev.latvian.mods:rhino", version.ref = "rhino" }
architectury        = { module = "dev.architectury:architectury-neoforge", version.ref = "architectury" }
clothconfig         = { module = "me.shedaniel.cloth:cloth-config-neoforge", version.ref = "clothconfig" }
theoneprobe         = { module = "mcjty.theoneprobe:theoneprobe", version.ref = "theoneprobe" }
curios              = { module = "top.theillusivec4.curios:curios-neoforge", version.ref = "curios" }
kotlinforforge      = { module = "thedarkcolour:kotlinforforge-neoforge", version.ref = "kotlinforforge" }
journeymap-api      = { module = "info.journeymap:journeymap-api-neoforge", version.ref = "journeyMapApi" }
shimmer             = { module = "com.lowdragmc.shimmer:Shimmer-forge", version.ref = "shimmer" }
ftblibrary          = { module = "dev.ftb.mods:ftb-library-neoforge", version.ref = "ftblibrary" }
ftbteams            = { module = "dev.ftb.mods:ftb-teams-neoforge", version.ref = "ftbteams" }
ftbquests           = { module = "dev.ftb.mods:ftb-quests-neoforge", version.ref = "ftbquests" }
ftbchunks           = { module = "dev.ftb.mods:ftb-chunks-neoforge", version.ref = "ftbchunks" }
resourcefullib      = { module = "com.teamresourceful.resourcefullib:resourcefullib-neoforge-1.21", version.ref = "resourcefullib" }
gamestages          = { module = "net.darkhax.gamestages:GameStages-Forge-1.20.3", version.ref = "gamestages" }
bookshelf           = { module = "net.darkhax.bookshelf:bookshelf-neoforge-1.21.1", version.ref = "bookshelf" }
ae2wtlib            = { module = "de.mari_023:ae2wtlib", version.ref = "ae2wtlib" }
# TODO update these once there's 1.21 versions
argonauts           = { module = "earth.terrarium.argonauts:argonauts-neoforge-1.20.4", version.ref = "argonauts" }
heracles            = { module = "earth.terrarium.heracles:heracles-forge-1.20.1", version.ref = "heracles" }

jade                = { module = "maven.modrinth:jade", version.ref = "jade" }
sodium              = { module = "maven.modrinth:sodium", version.ref = "sodium" }
iris                = { module = "maven.modrinth:iris", version.ref = "iris" }
modernfix           = { module = "maven.modrinth:modernfix", version.ref = "modernfix" }


cc-tweaked-core-api   = { module = "cc.tweaked:cc-tweaked-1.21.1-core-api", version.ref = "ccTweaked" }
cc-tweaked-forge-api  = { module = "cc.tweaked:cc-tweaked-1.21.1-forge-api", version.ref = "ccTweaked" }
cc-tweaked-forge-impl = { module = "cc.tweaked:cc-tweaked-1.21.1-forge", version.ref = "ccTweaked" }

worldstripper       = { module = "curse.maven:worldStripper-250603", version.ref = "worldStripper" }
javd                = { module = "curse.maven:javd-370890", version.ref = "javd" }
trenzalore          = { module = "curse.maven:trenzalore-870210", version.ref = "trenzalore" }
xaerosworldmap      = { module = "curse.maven:xaeros-world-map-317780", version.ref = "xaerosWorldMap" }
xaerosminimap       = { module = "curse.maven:xaeros-minimap-263420", version.ref = "xaerosMinimap" }
journeymap-forge    = { module = "curse.maven:journeymap-32274", version.ref = "journeyMap" }
spark               = { module = "curse.maven:spark-361579", version.ref = "spark" }
observable          = { module = "curse.maven:observable-509575", version.ref = "observable" }
## cursemaven as a backup ##
ftblibrary-cm       = { module = "curse.maven:ftb-library-forge-404465", version.ref = "ftblibrary-cm" }
ftbteams-cm         = { module = "curse.maven:ftb-teams-forge-404468", version.ref = "ftbteams-cm" }
ftbquests-cm        = { module = "curse.maven:ftb-quests-forge-289412", version.ref = "ftbquests-cm" }
ftbchunks-cm        = { module = "curse.maven:ftb-chunks-forge-314906", version.ref = "ftbchunks-cm" }

[bundles]
jei = ["jei-common-api", "jei-neoforge-api", "jei-neoforge-impl"]
rei = ["rei-plugin", "rei-neoforge"]
rei-runtime = ["rei-neoforge", "architectury", "clothconfig"]
kjs = ["kubejs", "rhino"]

