[versions]
minecraft = "1.21.1"
neoForge = "21.1.206"
loader = "4"
parchment = "2024.11.17" # https://parchmentmc.org/docs/getting-started
spotless = "8.1.0"
modDevGradle = "2.0.86"
lombok = "8.13.1"


[plugins]
modDevGradle            = { id = "net.neoforged.moddev", version.ref = "modDevGradle" }
spotless                = { id = "com.diffplug.spotless", version.ref = "spotless" }
lombok                  = { id = "io.freefair.lombok", version.ref = "lombok" }
