[versions]
minecraft = "1.21.1"
neoForge = "21.1.147"
loader = "4"
parchment = "2024.11.17" # https://parchmentmc.org/docs/getting-started
shadow = "8.3.5"
spotless = "8.1.0"
modDevGradle = "2.0.86"
lombok = "8.13.1"
jetbrains-annotations = "26.0.1"
mixin = "0.8.7"

[libraries]
minecraft               = { module = "com.mojang:minecraft", version.ref = "minecraft" }
neoForge                = { module = "net.neoforged:neoforge", version.ref = "neoForge" }
jetbrains-annotations   = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }

[plugins]
modDevGradle            = { id = "net.neoforged.moddev", version.ref = "modDevGradle" }
shadow                  = { id = "com.gradleup.shadow", version.ref = "shadow" }
spotless                = { id = "com.diffplug.spotless", version.ref = "spotless" }
lombok                  = { id = "io.freefair.lombok", version.ref = "lombok" }
